### ISSUE TITLE
PositionReport.RateOfTurn is I3, which is different than int8.

### ISSUE THREAD

**Issue by Waitak** [BertoldVdb/go-ais#8]
The `PositionReport` struct defines `RateOfTurn` as `int8`. This precludes the value of 128, which is used for "no turn information available". The source of the problem is a difference in interpretation of an AIS data type. [Eric Raymond's documentation](https://gpsd.gitlab.io/gpsd/AIVDM.html) for AIVDM messages defines this field as `I3`, which, if I'm understanding correctly, means "signed three digit decimal integer", which could (and does) have values that don't fit into an `int8`.

**Comment by simeonmiteff** [comment]
@Waitak good catch!

I believe the consequence is that `0b10000000` shoved into the `int8` represents -128. That doesn't is still distinct from the special value of -127 (turning left at more than 5deg/30s) so everything still fits in the `int8`, but still a bug because it would be a surprise to a package user going by the spec.

I'd be interested to hear @BertoldVdb 's take on this.

**Comment by Waitak** [comment]
I think that the simplest and correct fix would be to change `PositionReport.RateOfTurn` to an `int16`. The base problem, as mentioned, is that an `I3` doesn't fit into 8 bits (even if the expected values happen to (almost) fit into 8 bits).

**Comment by Waitak** [comment]
Added pull request with the above change.

**Comment by BertoldVdb** [comment]
Thanks. I was away for a while.
